"""update salary field

Revision ID: 6ff49cb41b8e
Revises: ca69a03b9e42
Create Date: 2021-10-20 17:18:03.444772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff49cb41b8e'
down_revision = 'ca69a03b9e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_salary', table_name='job')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_job_salary', 'job', ['salary'], unique=False)
    # ### end Alembic commands ###
