"""jobs

Revision ID: ca69a03b9e42
Revises: 24232227c6c5
Create Date: 2021-10-20 10:42:13.981593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca69a03b9e42'
down_revision = '24232227c6c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('salary', sa.String(length=100), nullable=True),
    sa.Column('skills', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_country'), 'job', ['country'], unique=False)
    op.create_index(op.f('ix_job_id'), 'job', ['id'], unique=False)
    op.create_index(op.f('ix_job_name'), 'job', ['name'], unique=False)
    op.create_index(op.f('ix_job_salary'), 'job', ['salary'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_salary'), table_name='job')
    op.drop_index(op.f('ix_job_name'), table_name='job')
    op.drop_index(op.f('ix_job_id'), table_name='job')
    op.drop_index(op.f('ix_job_country'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
